[melon]
title = "멜론 티켓"
url = "https://ticket.melon.com/csoon/index.htm"
entrySelector = "div ul[class='list_ticket_cont'] li"
titleSelector = "a[class='tit']"
linkSelector = "a[class='tit']"
contentSelector = "span[class='date']"
waitUntil = "networkidle"
onFail = "stale"

[interpark]
title = "인터파크 티켓"
url = "http://ticket.interpark.com/Webzine/Paper/TPNoticeList_iFrame.asp?bbsno=34&pageno=0&stext=&KindOfGoods=&Genre=&sort="
entrySelector = "tbody > tr"
titleSelector = "td.subject a"
linkSelector = "td.subject a"
contentSelector = "td[class='date']"
waitUntil = "networkidle"
onFail = "stale"

[interpark_m]
title = "인터파크 티켓 모바일"
url = "http://mticket.interpark.com/Notice/"
entrySelector = "div[class='list'] div.item"
titleSelector = "p[class='label']"
linkSelector = "a"
contentSelector = "dl[class='ticketOpen'] > dd"
imageSelector = "span img"
waitUntil = "networkidle"
onFail = "stale"

[yes24]
title = "예스24 티켓"
url = "http://ticket.yes24.com/New/Notice/NoticeMain.aspx"
entrySelector = " tbody tr:not(:first-child)"
titleSelector = "td a em"
linkSelector = "td:nth-child(2) > a"
contentSelector = "td:nth-child(3)"
waitUntil = "networkidle"
onFail = "stale"

[yes24_m]
title = "예스24 티켓 모바일"
url = "http://m.ticket.yes24.com/Notice/List.aspx?type=1"
entrySelector = "#BoardList > li"
titleSelector = "a > div.brd_name.limit_2ln"
linkSelector = "a[class='lnk_brd']"
contentSelector = "em[class='txt']"
waitUntil = "networkidle"
onFail = "stale"

[wemakeculture]
title = "위메프 공연티켓"
url = "https://ticket.wemakeprice.com/opennotice"
entrySelector = "tbody[id='notiList'] tr"
titleSelector = "div[class='title']"
linkSelector = "td a"
contentSelector = "span[class='date strong']"
imageSelector = "div[class='img'] img"
waitUntil = "networkidle"
onFail = "stale"

[ticketlink]
title = "티켓링크"
url = "http://www.ticketlink.co.kr/help/notice"
entrySelector = "tbody[id='nTableBody'] tr"
titleSelector = "td.tl.p_reative > a"
linkSelector = "td a"
contentSelector = "td[class='open_info']"
waitForSelector = ".basic_tbl"
onFail = "stale"

[ticketlink_m]
title = "티켓링크 모바일"
url = "http://m.ticketlink.co.kr/help/notice"
entrySelector = "#detail_content > li"
titleSelector = "h3"
linkSelector = "a"
contentSelector = "a > dl > dd:nth-child(2)"
onFail = "stale"

[naver_live]
title = "네이버 공연"
url = "https://live.naver.com/"
entrySelector = "ul.list-item li.item"
titleSelector = "div.detail-info a"
linkSelector = "div.detail-info a"
contentSelector = "p.date.ico-before"
imageSelector = "img._lazyImage"
waitUntil = "networkidle"
onFail = "stale"
